#
# This file is part of SOOP project.
#
# (c) Sébastien CHOMY <sebastien.chomy@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#
framework:
    validation:
        email_validation_mode: html5
